# This is a basic workflow to help you get started with Actions
# This demo workflow is disabled by default - use workflow_dispatch to run manually


name: "Newman Tests Demo"
on: 
  workflow_dispatch:  # Only run when manually triggered    

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export newman-report.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()  
        with:
          name: newman-test-results
          path: newman-report.html
